kind: ResourceQuota
apiVersion: v1
metadata:
  name: default
  annotations:
    massopen.cloud/quota-name: "small"
spec:
  hard:
    requests.cpu: '4'
    requests.memory: 8Gi
    limits.cpu: '4'
    limits.memory: 8Gi
    requests.storage: 40Gi
