- when: actually_delete_projects|default(false)|bool
  block:
    - name: "{{ project_name }} : lookup namespace"
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Namespace
        name: "{{ project_name }}"
      register: nsinfo

    - name: "{{ project_name }} : check namespace"
      fail:
        msg: "cannot delete this namespace"
      when: >-
        "massopen.cloud/project" not in nsinfo.resources[0].metadata.labels

    - name: "{{ project_name }} : delete namespace"
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Namespace
        name: "{{ project_name }}"
        namespace: "{{ project_name }}"

    - name: "{{ project_name }} : delete admin group"
      kubernetes.core.k8s:
        state: absent
        api_version: user.openshift.io/v1
        kind: Group
        name: "{{ project_name }}-admin"

    - name: "{{ project_name }} : delete member group"
      kubernetes.core.k8s:
        state: absent
        api_version: user.openshift.io/v1
        kind: Group
        name: "{{ project_name }}-member"
