- when: not project_dryrun|default(false)|bool
  block:
    - name: "{{ project_name }} : lookup namespace"
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Namespace
        name: "{{ project_name }}"
      register: nsinfo

    - name: "{{ project_name }} : check namespace"
      fail:
        msg: "cannot delete this namespace"
      when: >-
        "massopen.cloud/project" not in nsinfo.resources[0].metadata.labels

    - name: "{{ project_name }} : delete namespace"
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Namespace
        name: "{{ project_name }}"
        namespace: "{{ project_name }}"

    - name: "{{ project_name }} : delete groups"
      kubernetes.core.k8s:
        state: absent
        api_version: user.openshift.io/v1
        kind: Group
        name: "{{ project_name }}-{{ role }}"
      loop_control:
        loop_var: role
      loop:
        - admin
        - member
        - reader
