kind: LimitRange
apiVersion: v1
metadata:
  name: default
spec:
  limits:
    - type: Container
      default:
        cpu: "2"
        memory: "4Gi"
      defaultRequest:
        cpu: "2"
        memory: "2Gi"
