kind: ResourceQuota
apiVersion: v1
metadata:
  name: default
  annotations:
    massopen.cloud/quota-name: "large"
spec:
  hard:
    requests.cpu: '12'
    requests.memory: 32Gi
    limits.cpu: '12'
    limits.memory: 32Gi
    requests.storage: 80Gi
