kind: LimitRange
apiVersion: v1
metadata:
  name: default
spec:
  limits:
    - type: Container
      default:
        cpu: "4"
        memory: "8Gi"
      defaultRequest:
        cpu: "4"
        memory: "4Gi"
