kind: LimitRange
apiVersion: v1
metadata:
  name: default
spec:
  limits:
    - type: Container
      default:
        cpu: "1"
        memory: "2Gi"
      defaultRequest:
        cpu: "1"
        memory: "500Mi"
